ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQTqAe741/dN9Af1XLbRwuczANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwNTIyMDk0NTQyWhcNMzYw
  NTE5MDk0NTQyWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3GHaiYFQ8NiyvAENk8y9o7OevJqxO1oIn
  Huv2dVItNSiOzMwAJAeNGVo+69LEbJzkP5KA+1tqUaHM0SBqLwu81iEEOEb0aguN
  Qs7bYn/bN4slPZLzRT2hOVkgrPH4UEBiOCOlGcUIgeuQkQ/DfWZqKcqsVXrp+Vba
  t6NGU8iJz19h6C4SdbFCbqSTQEHLEpRx8l9jQ58qO/sXu6GhxlJ0DeTTF/AfJ43M
  ggwe3AHI0UVDbD5rMYzlmPnAtY4d39ceU6bzKtbq/7vAPubt3JkSKV1N6Vdj+9UA
  yCHu6bOpaHJIDJWtZM/HxU5SpsTpleKtqst/jV4aG7aF8wke16+PAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSbvIHb+1QfU4sknHLTvi4iqCPg
  qTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAcb+XEoliYcnv2ZJKOkiCTuFRsnWp8wnA1cKMmqT1QLYq
  QXiU48F6XvyS7LD8zFNWn5lW61jJNdzCNM33qyRq71uGghSkNYyl9W/j2WTogKLD
  arr2TFr8GVdmVw6hYn3V4mmsGp8rvYESf/m1ZJMODzmW5ymGEewrKSMh4CVaHyZY
  j/FftGXTz/wnlXe9AGhfY8RkBlUFrXWwpfpkYM1vm17pmsqomhFHttPNkY+r8r8z
  vAcXkngLfqp2U2MwglPtbGJkQr/q2Z/ppmESSgUA2mYm1cyJXUWMM1M0ukDxl17h
  WP0XF4C1GHPREB0amU53kUoyvbSlLPCRePoetzafyA==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDPjCCAiagAwIBAgIRAMfSpobXh4jQRPmo+dbsWfUwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI2MDUyMjIxNDkzMVoXDTI3
  MDUyMjIxNDkzMVowJzEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMQ4wDAYDVQQDEwVh
  ZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANJm5jTKsIEYQzO9
  BbuGWeb+vxMu1Lj72ormbsGoBfvG2uO1p073GZRrd5ZlsLGfE1hzMlZGaxp79uQI
  TAQTUJDnGUkb6/wXTkHXxro0t3dqhOcF6vXfi4sxnAUBm0SSlKg4KMey8BRnvlrr
  YETaE1vZxD0F+GNwWBtfrNoAi61xEyXPN4ReR50GRwtiK0SGrJrGo8/la4ELJUQD
  XAmEvectj5y8IcLh5C0rgrH2K1X0fuCF2n+3Ll9MJPP9PWk1t2h3jcwuKBZ+8mpg
  242uUn1khAYLF3bCUaA/z+fNuuuO7f5Bvyd2X09b+JhjWuGwRIuQ3B/ORH1oHetU
  Tsga6H0CAwEAAaNyMHAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUF
  BwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFJu8gdv7VB9T
  iyScctO+LiKoI+CpMBAGA1UdEQQJMAeCBWFkbWluMA0GCSqGSIb3DQEBCwUAA4IB
  AQB443f7clu72P2QMTY8WcuAw1ooSMwHzjgGsJIEGE1Fsj4Q9YG61KHepf9G4bAe
  vtFTrrBxtr2UTOcrO5gbQ2ve2SBbfODFWBZE/uG1OqvCAboyGt+/0FQFLK2vGQs4
  TBNI9fr77rVwWBASEaufr+UQcwShrn4CfoLDK7GBej7rX+dvA2dIvPQleFhQumE/
  0aI2TCEw1euSSW4b3L34SW2MUrlYxbC6o67yQm+Qns5yorbEbQk1PdofSV8IP7e1
  ks24gWmxi2wmh8h4v9MPrFRc1HbC+Vy99YuKS7VoYT/RYRdR8Dungd8BItDdup88
  XP/ZPJ0CscXdI/CKADLPQ8V4
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEA0mbmNMqwgRhDM70Fu4ZZ5v6/Ey7UuPvaiuZuwagF+8ba47Wn
  TvcZlGt3lmWwsZ8TWHMyVkZrGnv25AhMBBNQkOcZSRvr/BdOQdfGujS3d2qE5wXq
  9d+LizGcBQGbRJKUqDgox7LwFGe+WutgRNoTW9nEPQX4Y3BYG1+s2gCLrXETJc83
  hF5HnQZHC2IrRIasmsajz+VrgQslRANcCYS95y2PnLwhwuHkLSuCsfYrVfR+4IXa
  f7cuX0wk8/09aTW3aHeNzC4oFn7yamDbja5SfWSEBgsXdsJRoD/P5826647t/kG/
  J3ZfT1v4mGNa4bBEi5DcH85EfWgd61ROyBrofQIDAQABAoIBAAFpNj8BYviiqIS2
  zkyJJJ4zdCWVSVDqQ3dt/y0mSs/67+naBIK3joDbzaQBD5PJXNBZiWthsoMtdKTn
  11apqH8oRZeja8w3fctcPpVuGBLhcH26IO7ALofi78hqz9dAYmXUZpWcQhbo8TJb
  5LvheILDrZi5KwbDsJuSYy7dFRK3Lcq4mADWn3A+Oj5tSv4rUAe7zUgFoGDSVT7F
  WQy+GHucAqBYexrXsSEWFhJb3phzvfeMcwM/7YnqRQ+7WbzZgDq8+jx/2M+X4xnd
  vAXS62I2OgpHQaCOvQVlCdntUFuCrK+XgTKaUH3AftdJWzCl2nDrjjbvTSkgZmtB
  L2jF0cECgYEA9ziWK59gGCV8DsCdcfs4RJ3FA6SiMsJi4QbqhBiAuGqIG4vus/Zd
  DPdExxQ58dxZXl/8IOagatM30BW6QR5JfMNqtLNxcb7O4nHQxIxMHKYOy2nSXjQd
  Em5hj+rp7w48fafX+8iR+Nx+aumVhpY2//SqDe9S+Vb8Y41ArCwMSh0CgYEA2d+Z
  5hKk55vZJ09oJ/rI5vEpzt64W7lKvVWBy12QRJEJgKxDHmSqIsVbbZiG9EOHqTcx
  vBpvIgAawKBHXzKcYh02OA3prHmlwXrXzLSHqM3zbS0WHwLxNvZrpjuzk3dejnir
  H6GUQSGeAk5J6UMApIoWyBQ41dKCIICscNUByeECgYBHDr+zGCMRrayDvP9EJLYe
  ms5m5qosNs0e6tL7VuOgnhYy/LyGg3hpYqUlJ34kM3aIdsRMXJ2dNsqjB6u6Tc9H
  ig+gkrc3v2VNlvMvmzfBQEWeV/M8WnREuO9X42iL6qaeY2DkINk8E3xOlIcC4Sg7
  14INcU2DF2qB3rbJBfweTQKBgBuaT5YtgITzYsSvM8P06uUPYruZzgOY6xYnsiUA
  upllQq3xpSNBn6h+FoJBE7/4mkRfAMcTFkdZegozhDdUYymvB8J8SMGYO97SYGrH
  6HQDe7a2Qpo1Njg/ag4KfErPkcQ9F3kPcIf76VfjcUvDOF6gPBinLzgvzlqt0qsM
  4YghAoGAKh1HvVgQlMvw/yZJwS6wQipUygpss+jneoNWv4GHRoosahycqOtSEIyl
  m14onIY9gYhqkbfIo+dY+OIe+XFZsrNVaP2+6fuoq587EIAbzFdpEMPnHw2NCq7r
  YlqJQs9/4991fRlr9Ddw6HahKDQkHxqi4Uj6J8IlX0pNllLZpj0=
  -----END RSA PRIVATE KEY-----
api_connection_string: 127.0.0.1:8001
name: admin
